# Generated by Django 6.0.1 on 2026-02-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['teacher_code']},
        ),
        migrations.AddField(
            model_name='teacher',
            name='allocated',
            field=models.BooleanField(default=False),
        ),
    ]
