# Generated by Django 6.0.1 on 2026-02-01 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('class_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Randomly generated unique ID for the class', primary_key=True, serialize=False, unique=True)),
                ('class_name', models.CharField(help_text="The name of the class, e.g., 'West'", max_length=100)),
                ('stream', models.CharField(help_text="The stream or grade, e.g., 'Form 1', 'Grade 10'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['class_name', 'stream'],
            },
        ),
    ]
