# Generated by Django 6.0.1 on 2026-02-01 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={},
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='stream',
            field=models.CharField(max_length=50),
        ),
    ]
