# Generated by Django 6.0.1 on 2026-02-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
