# Generated by Django 6.0.1 on 2026-02-12 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableTemplate',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('day_start_time', models.TimeField()),
                ('lesson_duration_minutes', models.PositiveIntegerField()),
                ('lessons_per_day', models.PositiveIntegerField()),
                ('active_days', models.JSONField(default=list, help_text='List of active days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='TimetableBreak',
            fields=[
                ('break_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('break_name', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='timetable.timetabletemplate')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('template', 'position')},
            },
        ),
    ]
